### ISSUE TITLE
feat: Switch to `:toc: left` for the combined summary page

### ISSUE THREAD

**Issue by KartikSoneji** [OurTechCommunity/catchup#100]
As the number of summaries will grow, the header of the combined summary page will get longer and longer.
A better solution is to use `:toc: left`, which has the added benefit of allowing skipping to a specific summary.

https://github.com/OurTechCommunity/catchup/blob/082cdefdf8c84b82663536244a76b694bc4bbbb5/summary/combined-summary.adoc#L4

Maybe look into making the sidebar collapsable.
Maybe reduce the summaries by one header level to allow subsections to be visible.

**Comment by HarshKapadia2** [comment]
Oh yes, this is a good recommendation and we should implement this. Can you please open a PR for this?

> Maybe look into making the sidebar collapsable.

That is a good idea, but I don't think Asciidoctor has built-in support for it. We can build something for ourselves or contribute to Asciidoctor and we can do that asynchronously, but for now we should just shift the Table of Contents (ToC) to the left. The collapsible feature would anyways really be very useful only on smaller desktop screens, I guess, to make more space for the content. A left ToC should be manageable for larger/normal-sized desktop screens IMO.

> Maybe reduce the summaries by one header level to allow subsections to be visible.

I don't think this is really required, as the sub-sections are repetitive and can be scrolled to very easily. It will make the ToC list too long as well. (Remember that on mobile screens or very small screen sizes, the ToC will still appear on the top, so we would want to avoid unnecessary listings in the ToC to reduce its length.)

**Comment by HarshKapadia2** [comment]
Resolved in commit ae639b06e6316cf7f6d76bb36f72ea50761ed30b.
