### ISSUE TITLE
bugfix: Update actions dependent on deprecated versions of node

### ISSUE THREAD

**Issue by KMK-Git** [OurTechCommunity/catchup#107]
![Screenshot of workflow](https://user-images.githubusercontent.com/21997976/198813350-e451b4ae-383c-4421-953e-9792f2919b7f.png)
Screenshot from https://github.com/OurTechCommunity/catchup/actions/runs/3303128628

**Current scenario:**
- `actions/checkout` needs to be updated in all workflow files.
- `Eomm/why-don-t-you-tweet` needs to be updated in the twitter workflow files.

**Fixes:**
- The `actions/checkout` update is trivial since we just need to change `actions/checkout@v2` to `actions/checkout@v3`
- The `Eomm/why-don-t-you-tweet` update is more complicated since the action doesn't have an updated version with node 16+ as of now. There is an open issue in the action's repo https://github.com/Eomm/why-don-t-you-tweet/issues/64

**Deadline:**
From https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> We plan to migrate all actions to run on Node16 by **Summer 2023**

**Comment by HarshKapadia2** [comment]
Update:

> - The `actions/checkout` update is trivial since we just need to change `actions/checkout@v2` to `actions/checkout@v3`

The `checkout` GitHub Action still needs to be updated to v3. (Cc: @KartikSoneji)

> - The `Eomm/why-don-t-you-tweet` update is more complicated since the action doesn't have an updated version with node 16+ as of now. There is an open issue in the action's repo https://github.com/Eomm/why-don-t-you-tweet/issues/64

This has fortunately been fixed and we don't need to make any changes.
