### ISSUE TITLE
cleanup: Remove `alt-start` script from package.json

### ISSUE THREAD

**Issue by KartikSoneji** [OurTechCommunity/catchup#110]
https://github.com/OurTechCommunity/catchup/blob/8f57f8e59e92b5090306e1498cf2038615764080/package.json#L6-L9

The `alt-start` script was added in https://github.com/OurTechCommunity/catchup/commit/3e5c7384d5b6641f3761298d90d1c27709a98b74 but doesn't seem to be used at the moment.

Needs to be removed from `CONTRIBUTING.md` too.
https://github.com/OurTechCommunity/catchup/blob/507a2f54062005d4718814b5e3cf7c2a4fd9ba0d/CONTRIBUTING.md?plain=1#L16

**Comment by KartikSoneji** [comment]
cc: @HarshKapadia2

**Comment by HarshKapadia2** [comment]
As mentioned [in a comment of PR 97](https://github.com/OurTechCommunity/catchup/pull/97#issuecomment-1304655706):

> Replying to [Kartik's comment](https://github.com/OurTechCommunity/catchup/pull/97?notification_referrer_id=NT_kwDOAv0WwLM0NjEzNjYyNzkyOjUwMTQwODY0#discussion_r1009700727):
> 
> > The `alt-start` script was added in https://github.com/OurTechCommunity/catchup/commit/3e5c7384d5b6641f3761298d90d1c27709a98b74.
> > I don't remember why, it isn't used anywhere else in the repo either.
> > @HarshKapadia2 do you see any reason to keep it around?
> 
> It was added to work in Gitpod, as the original `npm run start` command was not working. ([CONTRIBUTING.md#gitpod-setup](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md#gitpod-setup))

**Comment by HarshKapadia2** [comment]
I hve not tested this again after new changes to the repository, so this might be outdated. We need to check this.

**Comment by KartikSoneji** [comment]
Let me know if `npm run start` doesn't work on GitPod, I'll investigate.

**Comment by HarshKapadia2** [comment]
Yeah `npm run start` works for me @KartikSoneji. I checked Gitpod.

**Comment by KartikSoneji** [comment]
Great, I'll remove `alt-start`.
