### ISSUE TITLE
cleanup: Migrate all markdown files to asciidoc

### ISSUE THREAD

**Issue by KartikSoneji** [OurTechCommunity/catchup#111]
The repo contains only three markdown files at the moment:
- [`CODE_OF_CONDUCT.md`](https://github.com/OurTechCommunity/catchup/blob/21da9e4e64d21575a1bf600e7daa36a1b511e723/CODE_OF_CONDUCT.md)
- [`CONTRIBUTING.md`](https://github.com/OurTechCommunity/catchup/blob/21da9e4e64d21575a1bf600e7daa36a1b511e723/CONTRIBUTING.md)
- [`README.md`](https://github.com/OurTechCommunity/catchup/blob/21da9e4e64d21575a1bf600e7daa36a1b511e723/README.md)

Changing them to asciidoc will make the repo more consistant and allow the files to be built and served on the catchup site if needed.

**Comment by HarshKapadia2** [comment]
NOTE: Even though Asciidoc and Markdown syntax is practically the same, the Markdown files will have to be formatted to follow the same syntax as used in the ohter Asciidoc files in the repo, to maintain consistency.

**Comment by HarshKapadia2** [comment]
I don't think we really need to do this, so I am closing the issue.
