### ISSUE TITLE
Redirect to OTC Talks Web Site.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#118]
Once the [OTC Talks](https://talks.ourtech.community) web site is finalized, we can redirect the ['Give a Talk' button](https://github.com/OurTechCommunity/catchup/blob/main/public/html/index.html#L144) on the CatchUp web app home page to the OTC Talks site.

**Comment by HarshKapadia2** [comment]
Should we redirect the 'Give a Talk' button to https://talks.ourtech.community or https://talks.ourtech.community/cfp? (We're currently redirecting to the latter.)

**Comment by tusharnankani** [comment]
Definitely, makes sense!
Fixing it.

**Comment by tusharnankani** [comment]
Fixed ✔
