### ISSUE TITLE
Error in superscript ordinals

### ISSUE THREAD

**Issue by AadityaNitin** [OurTechCommunity/catchup#128]
The superscript ordinals in the numbers ending with 11 should be "th" instead of "st"

![image](https://user-images.githubusercontent.com/81017088/209447293-1f55fb62-14a7-4a6c-96a9-ffa02550a374.png)

**Comment by tusharnankani** [comment]
We need to modify this: https://github.com/OurTechCommunity/catchup/blob/750d1d23e506e0627647c3d9b5170ef4f5ec629c/util/catchup-number.js#L19-L26

Easy fix: the error will only (hopefully) come for `x11`. Should be `th` instead of `st`.

**Comment by HarshKapadia2** [comment]
> Easy fix: the error will only (hopefully) come for `x11`. Should be `th` instead of `st`.

Numbers `x11`, `x12` and `x13` are all affected. They all should end with `th` rather than `st`, `nd` and `rd` respectively.

Eg: The current behaviour for OTC CatchUp no. `311` is to output `311st`, but it should be `311th`.

**Comment by HarshKapadia2** [comment]
Thank you so much for opening a PR, Tushar!
