### ISSUE TITLE
Video element overflows on summary pages when screen width is less than 700 px.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#132]
We add [a video](https://github.com/OurTechCommunity/catchup/blob/main/summary/static/img/oops.mp4) to indicate that we forgot to take a picture during a particular CatchUp session, for example in the [74th CatchUp summary](https://catchup.ourtech.community/summary/74).

We haven't added any size restrictions to that element, so maybe that's why it overflows on screens less than 700 px in width. The page becomes horizontally scrollable and can be zoomed out, when both of those should not be required.

This affects [the common summary page](https://catchup.ourtech.community/summary) and the individual summary pages with such a video included (Eg: [74th CatchUp summary](https://catchup.ourtech.community/summary/74)).

One thing to remember while assigning a width would be the we need to maintain the aspect ratio of the video. (This might be achieved using [the `aspect-ratio` property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio), but this is just a suggestion.)

Normal page load (overflow should not exist):

<img src="https://user-images.githubusercontent.com/50140864/213791683-2eb63c48-c7a4-4000-b174-819cf861b7bb.png" width="30%" />

Zoomed out (should not happen):

<img src="https://user-images.githubusercontent.com/50140864/213791345-0a550e03-4a3b-4fdb-abca-160520a27893.png" width="30%" />

**Comment by mohitgangwani** [comment]
Can you please link how the page is getting rendered? I want to see the html tree

**Comment by mohitgangwani** [comment]
Proposed solution: an easy fix would be to add width 100% to the styling of the video tag, the video will render according to the size available, taking 100% of it.

**Comment by mohitgangwani** [comment]
> Proposed solution: an easy fix would be to add width 100% to the styling of the video tag, the video will render according to the size available, taking 100% of it. Tried for multiple devices, it is working.

Any updates? @HarshKapadia2 @tusharnankani @SirusCodes

**Comment by tusharnankani** [comment]
> Can you please link how the page is getting rendered? I want to see the html tree

Here: 

> We add [a video](https://github.com/OurTechCommunity/catchup/blob/main/summary/static/img/oops.mp4) to indicate that we forgot to take a picture during a particular CatchUp session, for example in the [74th CatchUp summary](https://catchup.ourtech.community/summary/74).

---

> Proposed solution: an easy fix would be to add width 100% to the styling of the video tag, the video will render according to the size available, taking 100% of it. Tried for multiple devices, it is working.

Would you like to open a Pull Request? Feel free to make the changes in the [/summary/static/css](https://github.com/OurTechCommunity/catchup/blob/main/summary/static/css/summary-style.css)

**Comment by mohitgangwani** [comment]
> > Can you please link how the page is getting rendered? I want to see the html tree
> 
> Here: 
> 
> > We add [a video](https://github.com/OurTechCommunity/catchup/blob/main/summary/static/img/oops.mp4) to indicate that we forgot to take a picture during a particular CatchUp session, for example in the [74th CatchUp summary](https://catchup.ourtech.community/summary/74).
> 
> ---
> 
> > Proposed solution: an easy fix would be to add width 100% to the styling of the video tag, the video will render according to the size available, taking 100% of it. Tried for multiple devices, it is working.
> 
> Would you like to open a Pull Request? Feel free to make the changes in the [/summary/static/css](https://github.com/OurTechCommunity/catchup/blob/main/summary/static/css/summary-style.css)
> 
> 

Alright will do.
