### ISSUE TITLE
feat: A button to edit/make the summary better via PRs.. 

### ISSUE THREAD

**Issue by dheerajdlalwani** [OurTechCommunity/catchup#146]
![image](https://user-images.githubusercontent.com/52416311/226965519-a5e8c19f-bee6-4ac2-934f-12bed630e7cc.png)

The button can be added here^

Or......
Like NextJS documentation adds it in the footer

![image](https://user-images.githubusercontent.com/52416311/226978696-a5602795-8401-403c-bf72-749aa820421b.png)

**Comment by HarshKapadia2** [comment]
Good idea, @dheerajdlalwani!

Some options for the button text:
-	Suggest changes
-	Edit summary on GitHub

**Comment by HarshKapadia2** [comment]
> I'd like to work on this.

Awesome! Thank you!

> I'd like to request some clarification:
> 1. Are there any specifications about the appearance of the button?
> 1.1. In the Next.js example, it's just displayed as a link, is the same required here as well?

A link at the top of the page would be just fine!

> 2. Should the button direct them to the GitHub repo, or something more specific?

- For Individual summaries
   - The link should redirect to the summary directory pertaining to every CatchUp session (`summary/sessions/<catchup_number>`).
   - Example: The link on the 130th OTC CatchUp session summary page should redirect to `https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions/130`.
   - Individual summary template: https://github.com/OurTechCommunity/catchup/blob/main/summary/individual-summary.adoc
   - Hosted individual 130th summary: https://catchup.ourtech.community/summary/130
- For the combined summary
   - The link should redirect to `https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions`.
   - Combined summary template: https://github.com/OurTechCommunity/catchup/blob/main/summary/combined-summary-template.adoc
   - Hosted combined summary: https://catchup.ourtech.community/summary

Do let us know of you have any more questions! Also, do add pictures of how the pages look like, whenever you contribute!

Thank you!

**Comment by sushma1031** [comment]
I'm having trouble adding a link at the top of the page. This is my code for a test link:

```
= OTC CatchUp #{catchup_display_number} Summary
Our Tech Community
v1
:revremark: link:https://catchup.ourtech.community[Test Link^]
```

This is how it renders:
![Screenshot 2023-05-14 200943](https://github.com/OurTechCommunity/catchup/assets/123486589/4f04fe15-4d37-4bac-8448-3dde1bd1be40)

Could you please suggest the appropriate syntax?

Alternatively, I could add the link at the bottom:
![image](https://github.com/OurTechCommunity/catchup/assets/123486589/689ebec6-fd89-4ea5-b02b-4b6d4342eeb0)

**Comment by HarshKapadia2** [comment]
I think you're trying to add the link at the wrong place.

Try adding `link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions/{catchup_display_number}[Edit this summary on GitHub^]` above line no. 17 of the `individual-summary.adoc`:

https://github.com/OurTechCommunity/catchup/blob/72531547ec028e38f64c97c0621e5b8c5ccad2be/summary/individual-summary.adoc?plain=1#L17

**Comment by sushma1031** [comment]
I gave that a try, this is the result:
![image](https://github.com/OurTechCommunity/catchup/assets/123486589/84c7e0bc-f67a-41f8-9699-5567ec21fd6b)

If this is the required result, please let me know, I'll do the same for the combined summary as well

**Comment by HarshKapadia2** [comment]
Should we reduce the font size of the 'edit' link, @tusharnankani?

**Comment by HarshKapadia2** [comment]
@sushma1031 can you please try reducing the font size and send a screenshot of that?

Feel free to send pictures with any other looks that you think work better as well.

Cc: @tusharnankani

**Comment by sushma1031** [comment]
Reducing the font size to 1rem appears like this:
<img width="691" alt="1rem" src="https://github.com/OurTechCommunity/catchup/assets/123486589/88ca4e73-e573-47d2-8353-abc6519aae2e">

Code:
```
[.edit-summary-btn]
link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions/{catchup_display_number}[Edit this summary on GitHub^]
```
CSS
```
.edit-summary-btn a{
	font-size: 1rem;
}
```

**Comment by sushma1031** [comment]
I personally found the extra space at the top unappealing:
<img width="691" alt="1rem spacing" src="https://github.com/OurTechCommunity/catchup/assets/123486589/64016a1e-3fda-4a99-a017-263ec53e0de4">

Hence I tried to make it even using css relative position
<img width="958" alt="1rem with relative position" src="https://github.com/OurTechCommunity/catchup/assets/123486589/34f2f330-11f6-4516-9290-115b30dc87f9">

Let me know your thoughts

**Comment by sushma1031** [comment]
Applying 0.75 rem made it look to small according to me, however let me know your opinion:
<img width="799" alt="point75rem" src="https://github.com/OurTechCommunity/catchup/assets/123486589/ab4eaa6a-a845-4088-8f34-2c0ae393bcfd">

**Comment by tusharnankani** [comment]
Hey

Looks good, yeah.

> Should we reduce the font size of the 'edit' link, @tusharnankani?

Yes.

Also, what do you think if we push the button to the bottom?

![image](https://github.com/OurTechCommunity/catchup/assets/61280281/ddecc004-5844-4016-9d9a-84993d4b81f9)

Something like this at MDN: https://developer.mozilla.org/en-US/docs/Web/javascript

**Comment by sushma1031** [comment]
Sure @tusharnankani , I can try that. It would look similar to this, although here I haven't reduced the font size yet:

> Alternatively, I could add the link at the bottom: ![image](https://user-images.githubusercontent.com/123486589/238193173-689ebec6-fd89-4ea5-b02b-4b6d4342eeb0.png)

Also, should I add a message like in the MDN docs above the link, or is just the link sufficient?

**Comment by tusharnankani** [comment]
I definitely think it is a good idea to add enough context like MDN.

What do you think @OurTechCommunity/core?

**Comment by HarshKapadia2** [comment]
Yeah I think adding a section like MDN at the bottom is a nice idea!

@sushma1031 can you design something like MDN that you like? We can go ahead from there. Do post a screenshot!

**Comment by tusharnankani** [comment]
Let us know if you need any help!

**Comment by sushma1031** [comment]
I'll work on it.
I'd like to request some more information, such as what we want to include in this section, in addition to the edit summary link.

**Comment by tusharnankani** [comment]
Sure.

Here is a layout you could follow:

```
Improve the content on this page?

[Edit the summary on GitHub](https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/130/content.adoc).
[Report the content issue](https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20%3Cnum%3E%20summary&body=Enter%20summary%20URL%20and%20changes%20to%20be%20made:).
[View the source on GitHub](https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/130/content.adoc).

Want to get more involved? [Learn how to contribute](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md).

```

Renders like:

Improve the content on this page?

[Edit the summary on GitHub](https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/130/content.adoc).
[Report the content issue](https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20%3Cnum%3E%20summary&body=Enter%20summary%20URL%20and%20changes%20to%20be%20made:).
[View the source on GitHub](https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/130/content.adoc).

Want to get more involved? [Learn how to contribute](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md).

**Comment by HarshKapadia2** [comment]
Do modify the links to include the correct CatchUp numbers, @sushma1031 !

Thank you for the example, Tushar!

**Comment by sushma1031** [comment]
I'll make sure to include the respective numbers @HarshKapadia2.
Thank you for the layout @tusharnankani !

**Comment by sushma1031** [comment]
Here's how it looks now:
![image](https://github.com/OurTechCommunity/catchup/assets/123486589/20c18c7a-0dac-4814-a075-aa8260c1e6ed)

Here's my code:
```
[.improve-heading]
Want to improve the content of this page?

[.improve-buttons]
* link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions/{catchup_display_number}[Edit this summary on GitHub.^]
* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20%3C{catchup_display_number}%3E%20summary&body=Enter%20summary%20URL%20and%20changes%20to%20be%20made[Report the content issue.^]
* link:https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/{catchup_display_number}/content.adoc[View the source on GitHub.^]


[.contribute] 
Want to get more involved? link:https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md[Learn how to contribute.^]
```
Let me know if any changes are required.

Also, my CSS changes are being ignored by Git, as the summary-style.css is present in the .gitignore file. Could you please let me know what I should do?

**Comment by HarshKapadia2** [comment]
> Here's how it looks now: ![image](https://user-images.githubusercontent.com/123486589/241761203-20c18c7a-0dac-4814-a075-aa8260c1e6ed.png)

I like how this looks! What do y'all think @OurTechCommunity/core?

I think we need to debate on the position of this section. It looks good at the bottom, but I think it should be above the quotes and below the note with the blue icon. (Picture below.) (We might get rid of that note, but that's another issue - we really need to restructure our summary page.)

<img src="https://github.com/OurTechCommunity/catchup/assets/50140864/e9293b9e-f039-4ddb-9d45-1edfa89f6c2b" width="50%" />
<br />
<br />

> Also, my CSS changes are being ignored by Git, as the summary-style.css is present in the .gitignore file. Could you please let me know what I should do?

Summary styles are located in https://github.com/OurTechCommunity/catchup/blob/main/summary/static/css/summary-style.css, so please make your changes in that file. (I think the file that you're referring to is the file that is copied over to `public/css/summary` while building the site.)

**Comment by sushma1031** [comment]
> Summary styles are located in https://github.com/OurTechCommunity/catchup/blob/main/summary/static/css/summary-style.css, so please make your changes in that file. (I think the file that you're referring to is the file that is copied over to `public/css/summary` while building the site.)

I was trying to update the wrong file as you pointed out. Thanks for directing me to the right one!

**Comment by tusharnankani** [comment]
One second, just realized this is an issue. 

@sushma1031, please feel free to open a PR. 
The UI looks great :D

**Comment by tusharnankani** [comment]
> I think we need to debate on the position of this section. It looks good at the bottom, but I think it should be above the quotes and below the note with the blue icon. 

Yes, let's place the content above the horizontal rule above the quotes. Would look good hopefully!

> We might get rid of that note, but that's another issue - we really need to restructure our summary page.

Right. Let's figure that out later.

**Comment by sushma1031** [comment]
This is how it looks:
![image](https://github.com/OurTechCommunity/catchup/assets/123486589/f357095c-3db9-42b5-847a-34801fb0cb93)
I was wondering if I should change the colour of "Want to improve the content..." to match these sub-headings:
<img width="801" alt="Screenshot (112)" src="https://github.com/OurTechCommunity/catchup/assets/123486589/9460e835-8f15-49cf-af42-20302902a4ab">

**Comment by sushma1031** [comment]
Following the same layout for the combined summary page:
<img width="960" alt="Screenshot (113)" src="https://github.com/OurTechCommunity/catchup/assets/123486589/af3c9b78-d45c-43f6-a9c3-edf8826018c8">

Code:
```
[.improve-heading]
Want to improve the content of this page?

[.improve-buttons]
* link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions[Edit these summaries on GitHub.^]
* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20combined%20summary&body=Enter%20changes%20to%20be%20made[Report the content issue.^]
* link:https://github.com/OurTechCommunity/catchup/blob/main/summary/combined-summary-template.adoc[View the source on GitHub.^]


[.contribute]
Want to get more involved? link:https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md[Learn how to contribute.^]

```

**Comment by HarshKapadia2** [comment]
> I was wondering if I should change the colour of "Want to improve the content..." to match these sub-headings:
> <img width="801" alt="Screenshot (112)" src="https://github.com/OurTechCommunity/catchup/assets/123486589/9460e835-8f15-49cf-af42-20302902a4ab">

No, let's keep the normal black text for now.
