### ISSUE TITLE
New Telegram/Twitter Actions workflow error.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#171]
The new Twitter and Telegram GitHub Action workflow that was merged in 0d544594be01a11fc3f592a70e84c7222e97f48d is causing errors: https://github.com/OurTechCommunity/catchup/actions/runs/5496419873

Can you please resolve them, @KartikSoneji? Thank you!

**Comment by HarshKapadia2** [comment]
Please check all the workflows and do remember to delete the extra Tweets and Telegram messages! Thank you!

**Comment by KartikSoneji** [comment]
I used
`node util\get-seconds-until-ist-time.js` instead of
`node util/get-seconds-until-ist-time.js` 🤦 

Should be fixed by 011036c

**Comment by HarshKapadia2** [comment]
That was fixed, but now we have a new error: https://github.com/OurTechCommunity/catchup/actions/runs/5497391871

**Comment by HarshKapadia2** [comment]
Resolved in a bunch of commits from c27e13324cbde84099095b928320d804ec97f09d and before it.
