### ISSUE TITLE
Use containers for actions

### ISSUE THREAD

**Issue by SirusCodes** [OurTechCommunity/catchup#21]
Currently, we are using an Ubuntu container to run actions. It will be better if we can use Node v16 container.

**Comment by HarshKapadia2** [comment]
> Currently, we are using an Ubuntu container to run actions. It will be better if we can use Node v16 container.

Correction: Please do not change the `runs-on: ubuntu-latest` VM. On top of Ubuntu, we want to run a Node.js Docker container.

So the only change is adding a `container` key to all the reminder and joining workflow jobs, with the value being a Node.js Docker container.

**Comment by SirusCodes** [comment]
Ohh cool👍 my bad I thought that was the container

**Comment by SirusCodes** [comment]
> (Example: [HarshKapadia2/git_basics@`main`/.github/workflows/build-website.yml#L25-L26](https://github.com/HarshKapadia2/git_basics/blob/main/.github/workflows/build-website.yml?rgh-link-date=2021-12-27T08%3A39%3A50Z#L25-L26))

The link is broken.

**Comment by HarshKapadia2** [comment]
Fixed @SirusCodes

**Comment by KartikSoneji** [comment]
> Currently, we are using an Ubuntu container to run actions. It will be better if we can use Node v16 container.

Is there any specific reason to use the nodejs container?
We are not even installing any packages, so we just need node.
I think the nodejs container might slow the actions down with no real benefit.

**Comment by SirusCodes** [comment]
Current implementation is half setup of node and pulling the image would take more time imo.

We can create a PR and then probably compare them

**Comment by HarshKapadia2** [comment]
> Current implementation is half setup of node and pulling the image would take less time imo.

I was thinking this as well, because we're doing the following for every Action:

https://github.com/OurTechCommunity/catchup/blob/66dfaae7ed3e4ed6e82bdcd0b6871276b3bec14b/.github/workflows/tg-joining-msg.yaml#L19-L20

> I think the nodejs container might slow the actions down with no real benefit.

Doesn't caching come into picture here? Doesn't GitHub Actions cache repeatedly used images? I think it does, but I'm not sure.
As Darshan suggested, can we create a PR and compare the two? I'm not sure how we will measure this otherwise.
Thoughts, @KartikSoneji?

**Comment by KartikSoneji** [comment]
Before we do anything, can we double check if nodejs is already available on the runners?
I think it is:
([source](https://github.com/actions/runner-images#software-and-image-support))

![image](https://user-images.githubusercontent.com/25801283/198325016-17d9a564-b903-444f-bc07-73eb23cc00c5.png)

**Comment by HarshKapadia2** [comment]
Oh. I did not even think about that. Thank you for bringing it to our notice!

Well it appears that Node.js is supported, so the following two lines can be omitted from all the scripts in that case...

https://github.com/OurTechCommunity/catchup/blob/66dfaae7ed3e4ed6e82bdcd0b6871276b3bec14b/.github/workflows/tg-joining-msg.yaml#L19-L20

Again, we should test this first in a test repo.

**Comment by KartikSoneji** [comment]
As verified in #97, the default runner comes with nodejs pre-installed so installing it is not needed.
The step can be removed from the action.
