### ISSUE TITLE
Merge telegram and twitter actions

### ISSUE THREAD

**Issue by SirusCodes** [OurTechCommunity/catchup#22]
Currently, we have actions as:
- Reminder
1. Telegram
2. Twitter
- Catchup
1. Telegram
2. Twitter

This costs a total of 4 actions which could be done in 2.
So the proposal is to merge all the reminder actions in 1 and catchup in 1.

**Comment by HarshKapadia2** [comment]
CRON job timings for the reminder workflow should be `20 16 * * 6` and for the CatchUp workflow should be `30 11 * * 6`.

Please keep the Twitter job above the Telegram job in each workflow.
