### ISSUE TITLE
Missing Images in Summaries

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#231]
Images for summary numbers 53 and lower are missing from the web app (on both common and individual summary pages). This might be an issue with Deta (our current hosting provider) due to limited upload sizes (which has been an issue before), but is an assumption. Let's see if this issue persists once we migrate our web app (#207).

<img width="500" alt="image" src="https://github.com/user-attachments/assets/c3c7ae05-4821-404a-a596-60ee9e6e290a">

Cc: @KartikSoneji, @SirusCodes

**Comment by SirusCodes** [comment]
That's because of now we are getting images directly from githubraw. I was too lazy to update paths for all such edge cases🙃
