### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#4]
Create a custom 404 page.

**Comment by tusharnankani** [comment]
Hi

Do you want something like this? 

![image](https://user-images.githubusercontent.com/61280281/146821802-a6178ff6-e848-4595-80e9-674c1e00904e.png)

OR

![image](https://user-images.githubusercontent.com/61280281/146821768-dac4858e-8b31-4e4b-8275-057915aba13f.png)

Side Note: I just made some changes from the console on the [home page](https://catchup.ourtech.community).

**Comment by HarshKapadia2** [comment]
I like the 2nd option (404 Page Not Found).

Instead of the two buttons, can we just have one white button saying 'OTC CatchUp' that redirects to the CatchUp home page? What do you think?

**Comment by tusharnankani** [comment]
Sure, that will look good.

Here it goes: 

![image](https://user-images.githubusercontent.com/61280281/146964736-8c79b0f2-0ea7-47e5-b2b2-d2f7889e8f26.png)

Although, when it says the question: `Jump to something else instead?` 
So, the direct CTA can be both the buttons, the same buttons that will show up when redirected to the catchup page.

**Comment by HarshKapadia2** [comment]
Okay, so you would prefer '404 Page Not Found' with the two buttons? Go ahead. Do that. Open a PR.

Make sure you make necessary changes in https://github.com/OurTechCommunity/catchup/blob/main/index.js to serve the 404 page.
(Please replace the `res.end`s in these lines to serve the 404 page as well: https://github.com/OurTechCommunity/catchup/blob/main/index.js#L46-L68)

https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md should help you in setting up locally.

**Comment by tusharnankani** [comment]
Yes, will do!

Facing a problem [while installation](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md#:~:text=Run%20npm%20run%20test%20in%20the%20root%20directory%20of%20the%20project%20to%20build%20the%20summary%20site%20once%20and%20start%20a%20hot%20reload%20server.%20The%20web%20app%20should%20be%20accessible%20on%20http%3A//localhost%3A%3Cport%3E.%20(The%20port%20will%20appear%20in%20the%20server%20console.)) here:

![image](https://user-images.githubusercontent.com/61280281/146984757-f639c599-10d5-47a4-9004-adaec6231b45.png)

```
Error: Project key is not defined
    at Deta (C:\Users\Tushar Nankani\Desktop\Git\Open Source\catchup\node_modules\deta\dist\index.js:741:15)
    at Object.<anonymous> (C:\Users\Tushar Nankani\Desktop\Git\Open Source\catchup\index.js:10:14)
```

I guess some step is missing in the [CONTRIBUTING.md](https://github.com/OurTechCommunity/catchup/blob/main/CONTRIBUTING.md)

![image](https://user-images.githubusercontent.com/61280281/146984728-7c362812-0b81-4df2-bbcb-707448e7887e.png)

**Comment by HarshKapadia2** [comment]
Oh. Thank you for pointing this out.

Create a `.env` file in the root directory of the project with variables as mentioned in https://github.com/OurTechCommunity/catchup/blob/main/sample.env and add some random strings as values.
Eg: `DETA_PROJECT_KEY=lsjdbvkjsdbksbdkcjs`

Please LMK if this works, I'll add to the `CONTRIBUTING.md` file.

**Comment by tusharnankani** [comment]
Yes, working. Thank you!

![image](https://user-images.githubusercontent.com/61280281/147001664-ae9b2111-fa71-446f-ac9d-47a4bc7ef075.png)

Opened an issue for the same: #8
