### ISSUE TITLE
Use meet screenshot as OG image for CatchUp summary

### ISSUE THREAD

**Issue by HardikRa** [OurTechCommunity/catchup#69]
When the summary link preview loads on any app such as WhatsApp etc, the link preview should contain the screenshot taken during the meet of people present

**Comment by HarshKapadia2** [comment]
Thank you raising the issue, @HardikRa.

We need to look into which of the following we want to keep as the OG image:
- OTC CatchUp meet screenshot
- CatchUp summary page screenshot
- Only CatchUp summary number as text on an image

NOTE: Check issue #3.

**Comment by HardikRa** [comment]
Any community is made of the people in it, which is why I believe it is better to use the meet screenshot as the OG image :)

**Comment by sreekaransrinath** [comment]
I agree with you @HardikRa, but from a design perspective, it can look very odd. I vote to keep it as-is

**Comment by KartikSoneji** [comment]
Closing this since it's already covered by #3
