### ISSUE TITLE
Missing image file for catchup #74

### ISSUE THREAD

**Issue by sreekaransrinath** [OurTechCommunity/catchup#92]
https://github.com/OurTechCommunity/catchup/tree/main/summary/static/img

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/50989977/194955497-ce314e9a-48a5-41ea-8fc4-c6fc082bd83c.png">

https://catchup.ourtech.community/summary/#74

<img width="931" alt="image" src="https://user-images.githubusercontent.com/50989977/194955540-4ce35674-0ae0-43e5-8789-87eec749fb41.png">

**Comment by sreekaransrinath** [comment]
We either need to add the missing image or remove the screenshot section for session 74

**Comment by SirusCodes** [comment]
Yeah, can you please add that.

**Comment by sreekaransrinath** [comment]
@SirusCodes no matter how far back I go in the tree, I'm unable to find the image for the 74th catch-up. What's the deal?

**Comment by SirusCodes** [comment]
@KartikSoneji are you sure that you have removed it or it was not ever there? Because I cannot find it in my fork.

@PranavDani can you find it?

**Comment by PranavDani** [comment]
The image is missing in the repo, need to check if I have it locally.

**Comment by SirusCodes** [comment]
https://twitter.com/OurTechComm/status/1515053187627061249?t=1fJgP91ppNxzj24irM3ekg&s=19


This confirms that the photo was not taken for 74th catchup 🥲

@sreekaransrinath you can remove the image from the doc

**Comment by KartikSoneji** [comment]
I'll add a commit with a custom summary without an image for CatchUp 74 to #76

**Comment by sreekaransrinath** [comment]
Done. Can one of you close out the issue when the PR gets merged?

**Comment by SirusCodes** [comment]
@KartikSoneji update the PR to auto close this as well

**Comment by SirusCodes** [comment]
Thanks @sreekaransrinath for pointing out the missing image❤️
